import {
  ArrowRight,
  ArrowUpRight,
  Building2,
  Calendar,
  Camera,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Clock,
  Eye,
  Gavel,
  Info,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Moon,
  Phone,
  Play,
  Quote,
  Scale,
  Search,
  Share2,
  Shield,
  Sparkles,
  Sun,
  TrendingUp,
  User,
  Users,
  X,
} from 'lucide-react'

const ICONS = {
  scale: Scale,
  gavel: Gavel,
  building: Building2,
  chart: TrendingUp,
  search: Search,
  shield: Shield,
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  check: Check,
  menu: Menu,
  close: X,
  sun: Sun,
  moon: Moon,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  phone: Phone,
  mail: Mail,
  mapPin: MapPin,
  clock: Clock,
  calendar: Calendar,
  linkedin: Share2,
  twitter: MessageCircle,
  instagram: Camera,
  youtube: Play,
  user: User,
  eye: Eye,
  info: Info,
  sparkles: Sparkles,
  quote: Quote,
  users: Users,
}

export default function Icon({ name, className = 'w-5 h-5', strokeWidth = 1.6 }) {
  const Component = ICONS[name]
  if (!Component) return null
  return <Component className={className} strokeWidth={strokeWidth} aria-hidden="true" />
}
